server {
    listen 80;

    location /api/inventory/ {
        proxy_pass http://inventory-service:8081/api/;
    }

    location /api/billing/ {
        proxy_pass http://billing-service:8082/api/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
